[build]
  command = "npm install"
  functions = "functions"

[[redirects]]
  from = "/COMP4537/labs/3/writeFile/*"
  to = "/.netlify/functions/writeFile"
  status = 200

[[redirects]]
  from = "/COMP4537/labs/3/readFile/file.txt"
  to = "/.netlify/functions/readFile"
  status = 200

[[redirects]]
  from = "/COMP4537/labs/3/greeting/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  [functions.timeout]
    default = 30